#!/usr/bin/env bash
# bootstrap_multi.sh — Create the multi-service template skeleton (Flask + gunicorn).
# Run from the repo root. Idempotent: safe to re-run.

set -euo pipefail

# --- Top-level files ---

cat > .gitignore <<'EOF'
# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
*.egg-info/
.pytest_cache/
.mypy_cache/
.ruff_cache/

# Virtual environments
.venv/
venv/
env/

# Environment files (NEVER commit secrets)
.env
.env.local
.env.*.local
!.env.example

# Editor/IDE
.vscode/
.idea/
*.swp
.DS_Store

# ML data and model artifacts (large, generated, or sensitive)
data/**/raw/*
data/**/interim/*
data/**/processed/*
data/**/external/*
!data/**/.gitkeep
!data/**/README.md

models/**/*
!models/**/.gitkeep
!models/**/README.md

# Frontend
node_modules/
.next/
dist/
build/

# Logs
*.log
EOF

cat > .env.example <<'EOF'
# Copy this file to .env and fill in real values. NEVER commit .env.

# --- service_a ---
SERVICE_A_DB_USER=postgres
SERVICE_A_DB_PASSWORD=changeme
SERVICE_A_DB_NAME=service_a
SERVICE_A_DATABASE_URL=postgresql://postgres:changeme@service_a_db:5432/service_a

# --- External APIs ---
ANTHROPIC_API_KEY=
EOF

# --- backend/ ---
mkdir -p backend
cat > backend/requirements.txt <<'EOF'
# Dependencies for ALL backend services.
flask==3.1.3
gunicorn==25.3.0
pydantic>=2.0
pydantic-settings>=2.0
anthropic>=0.40

# Database (uncomment when adding persistence)
# sqlalchemy>=2.0
# alembic>=1.13
# psycopg2-binary>=2.9
EOF

cat > backend/Dockerfile <<'EOF'
FROM python:3.12-slim
WORKDIR /app/backend
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/ .
# Override CMD per service when running:
CMD ["gunicorn", "service_a.api.main:app", "--bind", "0.0.0.0:8000", "--workers", "4"]
EOF

# --- backend/service_a/ skeleton ---
SERVICE=service_a
mkdir -p backend/$SERVICE/{api,core,db,models,repositories,services,ml_models,clients,schemas,utils}

# Package __init__.py files
touch backend/$SERVICE/__init__.py
for sub in api core db models repositories services ml_models clients schemas utils; do
  touch backend/$SERVICE/$sub/__init__.py
done

# A minimal Flask api/main.py — routes prefixed with /your_pkg/ for namespacing
# behind a reverse proxy. Trailing slash on the home route lets both
# /your_pkg and /your_pkg/ work.
cat > backend/$SERVICE/api/main.py <<'EOF'
from flask import Flask, jsonify

app = Flask(__name__)


@app.get("/service_a/")
def home():
    return jsonify({"status": "ok", "message": "service_a is running"})


@app.get("/service_a/health")
def health():
    return jsonify({"status": "ok"})
EOF

# A minimal core/config.py
cat > backend/$SERVICE/core/config.py <<'EOF'
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_prefix="SERVICE_A_")

    database_url: str = ""


settings = Settings()
EOF

# --- ml/ ---
mkdir -p ml/$SERVICE/{configs,data,training,evaluation,notebooks}
touch ml/$SERVICE/configs/.gitkeep
touch ml/$SERVICE/data/.gitkeep
touch ml/$SERVICE/training/.gitkeep
touch ml/$SERVICE/evaluation/.gitkeep
touch ml/$SERVICE/notebooks/.gitkeep

cat > ml/requirements.txt <<'EOF'
# Heavy training dependencies. Installed in a separate venv from backend/.
# torch>=2.4
# transformers>=4.40
# datasets>=2.20
# accelerate>=0.30
# wandb>=0.17
EOF

# --- frontend/ ---
mkdir -p frontend
cat > frontend/README.md <<'EOF'
# Frontend

Stack: TBD. Populate when chosen (e.g., Next.js + TypeScript).

When ready, this folder will contain:

- `package.json`
- `Dockerfile`
- Source files (`src/`, `app/`, etc., depending on framework)
EOF

# --- data/ ---
mkdir -p data/$SERVICE/{raw,interim,processed,external}
touch data/$SERVICE/raw/.gitkeep
touch data/$SERVICE/interim/.gitkeep
touch data/$SERVICE/processed/.gitkeep
touch data/$SERVICE/external/.gitkeep

cat > data/README.md <<'EOF'
# Data

ML data folder. **All contents are gitignored** — only the structure and this README are tracked.

Per-service split:

- `data/<service>/raw/` — immutable original data, never edited
- `data/<service>/interim/` — intermediate processing artifacts
- `data/<service>/processed/` — final data fed into training
- `data/<service>/external/` — third-party data not generated by this project

Note: this folder is for **ML data**. Application database contents live inside the running database container, not here.
EOF

# --- models/ ---
mkdir -p models/$SERVICE
touch models/$SERVICE/.gitkeep

cat > models/README.md <<'EOF'
# Models

Trained ML model artifacts (weights, checkpoints). **All contents are gitignored** — only the structure and this README are tracked.

When you outgrow local files, point this at a model registry (MLflow, W&B, Hugging Face Hub) or a versioned cloud bucket.
EOF

# --- scripts/ ---
mkdir -p scripts
cat > scripts/README.md <<'EOF'
# Scripts

One-off CLI scripts: data downloads, database seeding, migrations bootstrapping, etc.
EOF

# --- docs/ ---
mkdir -p docs
[ ! -f docs/architecture.md ] && cat > docs/architecture.md <<'EOF'
# Architecture

High-level architecture notes for this project. Fill in:

- Services and their responsibilities
- External dependencies (APIs, databases)
- Data flow
- Deployment topology
EOF

echo "✅ Skeleton created."
echo ""
echo "Next steps:"
echo "  1. Replace 'service_a' with your real service name (rename folder + grep)."
echo "  2. cd backend && python3 -m venv venv && source venv/bin/activate"
echo "  3. pip install -r requirements.txt"
echo "  4. Run dev server (auto-reload):"
echo "       flask --app service_a.api.main run --host 0.0.0.0 --port 8000"
echo "  5. OR Run via gunicorn (production-style):"
echo "       gunicorn --bind 127.0.0.1:8000 service_a.api.main:app"
echo "  6. Verify:"
echo "       curl http://127.0.0.1:8000/health"